CREATE ALIAS IF NOT EXISTS TIMEDIFF DETERMINISTIC FOR "name.valery1707.core.db.h2.TimeFunctions.TimeDiff";
CREATE ALIAS IF NOT EXISTS TIME_TO_SEC DETERMINISTIC FOR "name.valery1707.core.db.h2.TimeFunctions.TimeToSec";
